config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'users/edit'
  #get 'users/profile'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :about

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save :sanitize_text
  

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true,
            length: { minimun: 5, maximum: 10 }
  validates :name, presence: true
  validates :email, presence: true,
            uniqueness: {case_sensitive: false},
            length: {maximum: 25},
            format: {with: VALID_EMAIL_REGEX}
  
  def sanitize_text
    #self.username = username.downcase
    #self.name = name.titleize
    self.email = email.downcase
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username name phone email password])

  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end
  
  def show
  end

  def new
    @user = User.new
  end
    
  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end    
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was succesfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destoy
    redirect_to users_url, notice: "User was successfully deleted."
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :name, :phone) # :country, :city, :bio, :image, social_attributes: [])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1>I'm the about page</h1>

app/views/home/_header.html.erb
<nav class="nav">
  <ul class="nav-links">
    <a href="<%= root_path %>" id="logoclick" class="nav-links"><%= image_tag "logo.png", id:"logo" %>LinkBranches</a>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Users", users_path %></li>
    <% if user_signed_in? %>
    <li><%= link_to "Profile", current_user%></li>
    <% end %>
  </ul>
</nav>
<div class="session">
  <% if user_signed_in? %>
  <a id="signup"><button><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %></button></a>
  <% else %>
  <a id="login" href="<%= new_user_session_path %>">Log in</a>
  <a id="signup" href="<%= new_user_registration_path %>"><button>SIGN UP FREE</button></a>
  <% end %>
</div>

app/views/home/index.html.erb
<div> <!-- Second head -->
  <h1>The Only Link You’ll Ever Need</h1>

Connect audiences to all of your content with just one link
</div>
<div> <!-- Phone anime -->
</div>
					

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linktree</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'home/header' %>
    </header>

    <main>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
    <!--footer>
    </footer-->
  </body>
</html>

app/views/users/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>
here??
<%= form_with(model: @user) do |f| %>
<%#= render "users/shared/error_messages", resource: resource %>

<div class="field">
  <%= f.label :current_username %><br />
  <%= f.text_area :@username, autofocus: true, autocomplete: "username" %>
</div>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_area :name, autocomplete: "name" %>
</div>

<div class="field">
  <%= f.label :phone %><br />
  <%= f.text_field :email, autofocus: true, autocomplete: "phonee" %>
</div>

<div class="field">
  <%= f.label :country %><br />
  <%= f.text_field :email, autofocus: true, autocomplete: "country" %>
</div>
  
<div class="field">
  <%= f.label :city %><br />
  <%= f.text_field :email, autocomplete: "city" %>
</div>

<div class="field">
  <%= f.label :bio %><br />
  <%= f.text_area :bio, autocomplete: "bio" %>
</div>

<div class="field">
  <%= f.label :email %><br />
  <%= f.email_field :email, autocomplete: "email" %>
</div>
<%# if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
<div>Currently waiting confirmation for: <%#= resource.unconfirmed_email %></div>
<%# end %>

<div class="field">
  <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password, autocomplete: "new-password" %>
  <% if @minimum_password_length %>
  <br />
  <em><%= @minimum_password_length %> characters minimum</em>
  <% end %>
</div>

<div class="field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
</div>

<div class="field">
  <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
  <%= f.password_field :current_password, autocomplete: "current-password" %>
</div>

<div class="actions">
  <%= f.submit "Update" %>
</div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h1>Contacts</h1>

<div class="table-responsive mt-3">
  <table class="table table-hover align-middle">
    <thead class="table-dark align-middle">
      <tr>
        <th></th>
        <th>Username</th>
        <th>Name</th>
        <th>Location</th>
	<th>email</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <!--td><# link_to image_tag(user.image.variant(resize_to_fill: [100, 100]), class: 'image-list'), user.imag-->
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.city %>, <%= user.country %></td>
	<td><%= user.email %></td>
	<td><%= link_to "Visit", user, class: 'btn btn-primary btn-sm' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br/>

<%#= link_to 'New Contact', new_user_path, class: 'btn btn-primary' %>

app/views/users/pprofile.html.erb
<div>
</div>
<div>
  <% if user_signed_in? %>
  <h5><%= link_to "Edit info", current_user %></h5>
  <h5><%= link_to "Edit info2", edit_user_registration_path %></h5>
  <% else %>
  <%= link_to "User info", users_path %>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if user_signed_in? and current_user.id == @user.id %>
<h5><%= link_to "Edit info1", edit_user_path(@user) %></h5> <!-- get user/edit--user/edit -->
<h5><%= link_to "Edit info2", edit_user_registration_path %></h5>
<h5><%#= link_to "Edit info3", users_edit_path(@user) %></h5>
<% end %>

<div class="card w-50">
  <nav class="panel">
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%# = gravatar_image_tag(user.email, size: 64, alt: user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= @user.name %></strong><br />
              <small><%= @user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="">
        <div class="level-item has-centered-text">
          <div>
           <h5>Hi men</h5>
          </div>
        </div>
        </div>
      </div>
    </div>
  </nav>
</div>

<%= link_to "Back to users", users_path %>